language: python
sudo: false
branches:
  only:
    - master
python:
  - 3.5
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - npm install
script:
  - nosetests --with-coverage --cover-package=cunhajacaiu
after_success:
  - coveralls
addons:
  code_climate:
    repo_token: 8e130a27a9b4f788cdee7ea7e3a10982d50210d002fbc14794f63a501e879e1a
